[package]
name = "hyprain"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "hyprain"
path = "hyprain/main.rs"

[dependencies]
hyprain_core = { path = "hyprain/hyprain-core" }

[workspace]
members = [
  "hyprain/hyprain-alttab",
  "hyprain/hyprain-bar",
  "hyprain/hyprain-core",
  "hyprain/hyprain-daemon",
  "hyprain/hyprain-dock",
  "hyprain/hyprain-notify",
  "hyprain/hyprain-settings"
]
resolver = "2"

[workspace.dependencies]
log = "0.4"
