[package]
name = "hyprain"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "hyprain"
path = "hyprain/main.rs"

[dependencies]
hyprain_core = { path = "hyprain/hyprain-core" }
log = { workspace = true }
env_logger = { workspace = true }
tokio = { workspace = true }


[workspace]
members = [
  "hyprain/hyprain-alttab",
  "hyprain/hyprain-bar",
  "hyprain/hyprain-core",
  "hyprain/hyprain-daemon",
  "hyprain/hyprain-dock",
  "hyprain/hyprain-notify",
  "hyprain/hyprain-settings"
]
resolver = "2"

[workspace.dependencies]
log = "0.4"
env_logger = "0.11.3"
tokio = { version = "1", features = ["full"] }
colorsys = { version = "0.7.3" }
zbus = { version = "5", default-features = false, features = ["tokio"] }
serde = { version = "1.0"}
zvariant = { version = "5.0" }

